import React, { useState, useMemo, useRef } from 'react';
import { ErrorDataPoint, ForecastResponse, ModelType } from '../types/gnss';
import { Layers, ZoomIn, Info, CheckCircle2, TrendingUp } from 'lucide-react';

export type ErrorAxis = 'clock' | 'x' | 'y' | 'z' | 'magnitude3D' | 'all';

interface MainForecastGraphProps {
  historicalData: ErrorDataPoint[];
  forecastResult: ForecastResponse;
  selectedAxis: ErrorAxis;
  onSelectAxis: (axis: ErrorAxis) => void;
  selectedModel: ModelType;
}

export const MainForecastGraph: React.FC<MainForecastGraphProps> = ({
  historicalData,
  forecastResult,
  selectedAxis,
  onSelectAxis,
  selectedModel
}) => {
  const [viewWindow, setViewWindow] = useState<'8days' | '48h' | 'day8'>('48h');
  const [hoverIndex, setHoverIndex] = useState<number | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  // Combine historical (Days 1-7: 672 points) and forecast (Day 8: 96 points) into continuous timeline
  const combinedTimeline = useMemo(() => {
    const points: Array<{
      time: string;
      timestamp: number;
      isHistory: boolean;
      isNow: boolean;
      clock: number;
      x: number;
      y: number;
      z: number;
      magnitude3D: number;
      predClock?: number;
      predX?: number;
      predY?: number;
      predZ?: number;
      pred3D?: number;
      clockLower?: number;
      clockUpper?: number;
      xLower?: number;
      xUpper?: number;
      yLower?: number;
      yUpper?: number;
      zLower?: number;
      zUpper?: number;
      actualClock?: number;
      actualX?: number;
      actualY?: number;
      actualZ?: number;
      actual3D?: number;
    }> = [];

    // History points (Days 1-7)
    historicalData.forEach((d, idx) => {
      const isNow = idx === historicalData.length - 1;
      points.push({
        time: d.time,
        timestamp: d.timestamp,
        isHistory: true,
        isNow,
        clock: d.clockError,
        x: d.xError,
        y: d.yError,
        z: d.zError,
        magnitude3D: d.magnitude3D,
        predClock: isNow ? d.clockError : undefined,
        predX: isNow ? d.xError : undefined,
        predY: isNow ? d.yError : undefined,
        predZ: isNow ? d.zError : undefined,
        pred3D: isNow ? d.magnitude3D : undefined,
        clockLower: isNow ? d.clockError : undefined,
        clockUpper: isNow ? d.clockError : undefined,
      });
    });

    // Forecast points (Day 8 generated by XGBoost)
    forecastResult.points.forEach((p) => {
      points.push({
        time: p.time,
        timestamp: p.timestamp,
        isHistory: false,
        isNow: false,
        clock: p.predictedClock,
        x: p.predictedX,
        y: p.predictedY,
        z: p.predictedZ,
        magnitude3D: p.predicted3D,
        predClock: p.predictedClock,
        predX: p.predictedX,
        predY: p.predictedY,
        predZ: p.predictedZ,
        pred3D: p.predicted3D,
        clockLower: p.clockLower,
        clockUpper: p.clockUpper,
        xLower: p.xLower,
        xUpper: p.xUpper,
        yLower: p.yLower,
        yUpper: p.yUpper,
        zLower: p.zLower,
        zUpper: p.zUpper,
        actualClock: p.actualClock,
        actualX: p.actualX,
        actualY: p.actualY,
        actualZ: p.actualZ,
        actual3D: p.actual3D
      });
    });

    return points;
  }, [historicalData, forecastResult.points]);

  // Filter based on view window
  const activePoints = useMemo(() => {
    if (viewWindow === '8days') return combinedTimeline;
    if (viewWindow === '48h') {
      // Last 96 points of history + 96 forecast points = 192 pts
      const nowIdx = historicalData.length - 1;
      const startIdx = Math.max(0, nowIdx - 96);
      return combinedTimeline.slice(startIdx);
    }
    // Day 8 validation focus: last 8 points of history + 96 forecast points
    const nowIdx = historicalData.length - 1;
    return combinedTimeline.slice(Math.max(0, nowIdx - 8));
  }, [combinedTimeline, viewWindow, historicalData.length]);

  // Axis configuration & data getters
  const axisConfig = useMemo(() => {
    switch (selectedAxis) {
      case 'x':
        return {
          title: 'Ephemeris Along-Track Error (X)',
          unit: 'meters (m)',
          color: '#38bdf8', // sky-400
          actualColor: '#94a3b8',
          getVal: (p: typeof activePoints[0]) => p.x,
          getPred: (p: typeof activePoints[0]) => p.predX,
          getActual: (p: typeof activePoints[0]) => p.actualX,
          getLower: (p: typeof activePoints[0]) => p.xLower,
          getUpper: (p: typeof activePoints[0]) => p.xUpper,
        };
      case 'y':
        return {
          title: 'Ephemeris Radial Error (Y)',
          unit: 'meters (m)',
          color: '#a855f7', // purple-500
          actualColor: '#94a3b8',
          getVal: (p: typeof activePoints[0]) => p.y,
          getPred: (p: typeof activePoints[0]) => p.predY,
          getActual: (p: typeof activePoints[0]) => p.actualY,
          getLower: (p: typeof activePoints[0]) => p.yLower,
          getUpper: (p: typeof activePoints[0]) => p.yUpper,
        };
      case 'z':
        return {
          title: 'Ephemeris Cross-Track Error (Z)',
          unit: 'meters (m)',
          color: '#ec4899', // pink-500
          actualColor: '#94a3b8',
          getVal: (p: typeof activePoints[0]) => p.z,
          getPred: (p: typeof activePoints[0]) => p.predZ,
          getActual: (p: typeof activePoints[0]) => p.actualZ,
          getLower: (p: typeof activePoints[0]) => p.zLower,
          getUpper: (p: typeof activePoints[0]) => p.zUpper,
        };
      case 'magnitude3D':
        return {
          title: 'Derived 3D Ephemeris Magnitude (E_3D = √(X²+Y²+Z²))',
          unit: 'meters (m)',
          color: '#f59e0b', // amber-500
          actualColor: '#94a3b8',
          getVal: (p: typeof activePoints[0]) => p.magnitude3D,
          getPred: (p: typeof activePoints[0]) => p.pred3D,
          getActual: (p: typeof activePoints[0]) => p.actual3D,
          getLower: (p: typeof activePoints[0]) => Math.max(0, p.pred3D - getPredictionInterval(p)),
          getUpper: (p: typeof activePoints[0]) => p.pred3D + getPredictionInterval(p),
        };
      case 'clock':
      default:
        return {
          title: 'Satellite Clock Error (Δt_clk)',
          unit: 'meters equivalent (m)',
          color: '#06b6d4', // cyan-500
          actualColor: '#94a3b8',
          getVal: (p: typeof activePoints[0]) => p.clock,
          getPred: (p: typeof activePoints[0]) => p.predClock,
          getActual: (p: typeof activePoints[0]) => p.actualClock,
          getLower: (p: typeof activePoints[0]) => p.clockLower,
          getUpper: (p: typeof activePoints[0]) => p.clockUpper,
        };
    }
  }, [selectedAxis, activePoints]);

  // Compute Y-Domain from all visible values (historical, predicted, actual)
  const yDomain = useMemo(() => {
    let min = Infinity;
    let max = -Infinity;

    activePoints.forEach((p) => {
      const v = axisConfig.getVal(p);
      const pred = axisConfig.getPred(p);
      const act = axisConfig.getActual(p);
      const lower = axisConfig.getLower(p);
      const upper = axisConfig.getUpper(p);

      [v, pred, act, lower, upper].forEach((val) => {
        if (typeof val === 'number' && !isNaN(val)) {
          if (val < min) min = val;
          if (val > max) max = val;
        }
      });
    });

    if (min === Infinity) { min = -1; max = 1; }
    // Add 15% padding
    const padding = (max - min) * 0.15 || 0.5;
    return { min: min - padding, max: max + padding };
  }, [activePoints, axisConfig]);

  // Coordinate scales
  const getX = (index: number) => {
    if (activePoints.length <= 1) return 50;
    return 50 + (index / Math.max(1, activePoints.length - 1)) * 900;
  };

  const getY = (val: number) => {
    const range = yDomain.max - yDomain.min || 1;
    const clamped = Math.max(yDomain.min, Math.min(yDomain.max, val));
    return 30 + 240 - ((clamped - yDomain.min) / range) * 240;
  };

  // Get prediction interval for a point (data-driven from residuals)
  const getPredictionInterval = (p: typeof activePoints[0]) => {
    const sigma = Math.max(
      0.01,
      (p.clockUpper - p.clockLower) / (1.96 * 2) || 0.1
    );
    // Interval widens with horizon: 15min → narrow, 24h → wider
    const stepRatio = Math.min(1, (p.stepIndex || 1) / 96);
    return sigma * (0.5 + 0.5 * stepRatio) * 1.96;
  };

  // Find the 'NOW' index in activePoints
  const nowIndex = activePoints.findIndex((p) => p.isNow);
  const nowX = nowIndex >= 0 ? getX(nowIndex) : 50;

  // Build SVG Paths
  const historyPath = useMemo(() => {
    const pts = activePoints.filter((p) => p.isHistory);
    if (pts.length === 0) return '';
    return pts
      .map((p, idx) => {
        const x = getX(idx);
        const y = getY(axisConfig.getVal(p));
        return `${idx === 0 ? 'M' : 'L'} ${x.toFixed(1)} ${y.toFixed(1)}`;
      })
      .join(' ');
  }, [activePoints, axisConfig, yDomain]);

  const forecastPath = useMemo(() => {
    const startIndex = nowIndex >= 0 ? nowIndex : 0;
    const pts = activePoints.slice(startIndex);
    if (pts.length === 0) return '';
    return pts
      .map((p, i) => {
        const x = getX(startIndex + i);
        const y = getY(axisConfig.getPred(p) ?? axisConfig.getVal(p));
        return `${i === 0 ? 'M' : 'L'} ${x.toFixed(1)} ${y.toFixed(1)}`;
      })
      .join(' ');
  }, [activePoints, nowIndex, axisConfig, yDomain]);

  const actualPath = useMemo(() => {
    const startIndex = nowIndex >= 0 ? nowIndex : 0;
    const pts = activePoints.slice(startIndex).filter((p) => p.actualClock !== undefined || p.actualX !== undefined);
    if (pts.length === 0) return '';
    return pts
      .map((p, i) => {
        const x = getX(startIndex + i);
        const y = getY(axisConfig.getActual(p) ?? axisConfig.getVal(p));
        return `${i === 0 ? 'M' : 'L'} ${x.toFixed(1)} ${y.toFixed(1)}`;
      })
      .join(' ');
  }, [activePoints, nowIndex, axisConfig, yDomain]);

  // Confidence Interval Area Polygon (data-driven prediction interval)
  const confidenceAreaPath = useMemo(() => {
    const startIndex = nowIndex >= 0 ? nowIndex : 0;
    const pts = activePoints.slice(startIndex);
    if (pts.length < 2) return '';

    const upperPts = pts.map((p, i) => {
      const x = getX(startIndex + i);
      const upperVal = axisConfig.getUpper(p) ?? axisConfig.getPred(p) ?? axisConfig.getVal(p);
      return `${x.toFixed(1)},${getY(upperVal).toFixed(1)}`;
    });

    const lowerPts = [...pts].reverse().map((p, i) => {
      const origIdx = pts.length - 1 - i;
      const x = getX(startIndex + origIdx);
      const lowerVal = axisConfig.getLower(p) ?? axisConfig.getPred(p) ?? axisConfig.getVal(p);
      return `${x.toFixed(1)},${getY(lowerVal).toFixed(1)}`;
    });

    return `M ${upperPts.join(' L ')} L ${lowerPts.join(' L ')} Z`;
  }, [activePoints, nowIndex, axisConfig, yDomain]);

  // Y-axis grid tick values
  const yTicks = useMemo(() => {
    const ticks: number[] = [];
    const count = 5;
    const step = (yDomain.max - yDomain.min) / count;
    for (let i = 0; i <= count; i++) {
      ticks.push(yDomain.min + i * step);
    }
    return ticks;
  }, [yDomain]);

  // Active hover point
  const hoveredPoint = hoverIndex !== null && hoverIndex >= 0 && hoverIndex < activePoints.length
    ? activePoints[hoverIndex]
    : null;

  // Format time display
  const formatTime = (timeStr: string) => timeStr.split(' ')[0] + ' ' + timeStr.split(' ')[1].split(':').slice(0,2).join(':');

  return (
    <div className="bg-slate-900/80 border border-slate-700 rounded-xl p-5 shadow-lg relative flex flex-col justify-between">
      {/* Header controls */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-3 pb-3 border-b border-slate-700">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-sm font-semibold text-white tracking-tight flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-cyan-400"></span>
              {axisConfig.title}
            </h2>
            <span className="px-1.5 py-0.5 rounded bg-slate-800/80 border border-slate-700/60 text-[10px] font-mono text-cyan-300">
              {axisConfig.unit}
            </span>
          </div>
          <p className="text-[11px] text-slate-400 mt-0.5">
            Historical (Days 1–7) • <strong className="text-cyan-400">NOW</strong> → Future 96 steps Day 8 — <strong className="text-cyan-400">XGBoost Forecast only</strong> (pure prediction, no ground truth shown)
          </p>
        </div>

        {/* View Window & Axis Controls */}
        <div className="flex flex-wrap items-center gap-2">
          {/* Axis Selector */}
          <div className="flex items-center bg-slate-950/80 p-0.5 rounded-lg border border-slate-700 text-xs">
            {['clock', 'x', 'y', 'z', 'magnitude3D'].map((axis) => (
              <button
                key={axis}
                onClick={() => onSelectAxis(axis)}
                className={`px-2 py-1 rounded text-xs font-medium transition-colors ${
                  selectedAxis === axis
                    ? 'bg-cyan-500 text-slate-950 font-bold shadow-sm'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                {axis === 'clock' && 'Clock'}
                {axis === 'x' && 'Ephem X'}
                {axis === 'y' && 'Ephem Y'}
                {axis === 'z' && 'Ephem Z'}
                {axis === 'magnitude3D' && '3D (E_3D)'}
              </button>
            ))}
          </div>

          {/* View Window */}
          <div className="flex items-center bg-slate-950/80 p-0.5 rounded-lg border border-slate-700 text-xs">
            <span className="text-slate-500 px-1.5 flex items-center gap-1">
              <ZoomIn className="w-3 h-3" />
            </span>
            <button
              onClick={() => setViewWindow('day8')}
              className={`px-2 py-1 rounded text-xs transition-colors ${
                viewWindow === 'day8' ? 'bg-slate-800 text-white font-medium' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Day 8
            </button>
            <button
              onClick={() => setViewWindow('48h')}
              className={`px-2 py-1 rounded text-xs transition-colors ${
                viewWindow === '48h' ? 'bg-slate-800 text-white font-medium' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              48h Window
            </button>
            <button
              onClick={() => setViewWindow('8days')}
              className={`px-2 py-1 rounded text-xs transition-colors ${
                viewWindow === '8days' ? 'bg-slate-800 text-white font-medium' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              8 Days
            </button>
          </div>
        </div>
      </div>

      {/* Main SVG Visualization Canvas */}
      <div
        ref={containerRef}
        className="relative w-full overflow-hidden mt-3 cursor-crosshair select-none"
        onMouseMove={(e) => {
          if (!containerRef.current) return;
          const rect = containerRef.current.getBoundingClientRect();
          const mouseX = e.clientX - rect.left;
          const relativeX = (mouseX - 50) / 950;
          const index = Math.round(relativeX * (activePoints.length - 1));
          if (index >= 0 && index < activePoints.length) {
            setHoverIndex(index);
          } else {
            setHoverIndex(null);
          }
        }}
        onMouseLeave={() => setHoverIndex(null)}
      >
        <svg
          viewBox="0 0 1000 360"
          className="w-full h-auto overflow-visible"
          preserveAspectRatio="none"
        >
          <defs>
            {/* Gradient for historical line */}
            <linearGradient id="historyGradient" x1="0%" y1="0%" x2="0%" y2="100%">
              <stop offset="0%" stopColor="#38bdf8" stopOpacity="0.8" />
              <stop offset="100%" stopColor="#0284c7" stopOpacity="0.4" />
            </linearGradient>

            {/* Gradient for confidence interval fill */}
            <linearGradient id="uncertaintyGradient" x1="0%" y1="0%" x2="0%" y2="100%">
              <stop offset="0%" stopColor={axisConfig.color} stopOpacity="0.25" />
              <stop offset="100%" stopColor={axisConfig.color} stopOpacity="0.04" />
            </linearGradient>
          </defs>

          {/* Zero baseline */}
          {yDomain.min <= 0 && yDomain.max >= 0 && (
            <line
              x1={50}
              y1={getY(0)}
              x2={950}
              y2={getY(0)}
              stroke="#334155"
              strokeDasharray="4 4"
              strokeWidth="1.2"
            />
          )}

          {/* Horizontal Grid lines */}
          {yTicks.map((tick, i) => (
            <g key={i}>
              <line
                x1={50}
                y1={getY(tick)}
                x2={950}
                y2={getY(tick)}
                stroke="#1e293b"
                strokeWidth="1"
              />
              <text
                x={42}
                y={getY(tick) + 4}
                fill="#64748b"
                fontSize="10"
                fontFamily="monospace"
                textAnchor="end"
              >
                {tick.toFixed(2)}
              </text>
            </g>
          ))}

          {/* Vertical NOW Dividing Line */}
          {nowX !== null && nowX > 50 && nowX < 950 && (
            <g>
              {/* Shaded future background (from NOW to end) */}
              <rect
                x={nowX}
                y={30}
                width={950 - nowX}
                height={270}
                fill="#0f172a"
                opacity="0.5"
              />
              {/* Vertical line */}
              <line
                x1={nowX}
                y1={30}
                x2={nowX}
                y2={300}
                stroke="#22d3ee"
                strokeWidth="2"
                strokeDasharray="6 3"
              />
              {/* "NOW" pill marker */}
              <rect
                x={nowX - 30}
                y={20}
                width="60"
                height="18"
                rx="4"
                fill="#06b6d4"
              />
              <text
                x={nowX}
                y={24}
                fill="#020617"
                fontSize="10"
                fontWeight="bold"
                fontFamily="sans-serif"
                textAnchor="middle"
              >
                NOW (Day 7)
              </text>
            </g>
          )}

          {/* Confidence interval area (data-driven 95% prediction interval) */}
          {confidenceAreaPath && (
            <path
              d={confidenceAreaPath}
              fill="url(#uncertaintyGradient)"
              stroke={axisConfig.color}
              strokeWidth="0.8"
              strokeDasharray="2 2"
              opacity="0.75"
            />
          )}

          {/* 1. Historical Line (Days 1–7 actual error values) */}
          {historyPath && (
            <path
              d={historyPath}
              fill="none"
              stroke="#94a3b8"
              strokeWidth="2.2"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          )}

          {/* Day 8 is prediction only — ground truth hidden as requested */}
          {/* 2. Predicted Future Error Line (Day 8 XGBoost forecast — live future) */}
          {forecastPath && (
            <path
              d={forecastPath}
              fill="none"
              stroke={axisConfig.color}
              strokeWidth="2.8"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          )}

          {/* Hover Crosshair & Highlights */}
          {hoveredPoint && hoverIndex !== null && (
            <g>
              <line
                x1={getX(hoverIndex)}
                y1={30}
                x2={getX(hoverIndex)}
                y2={300}
                stroke="#38bdf8"
                strokeWidth="1.5"
                strokeDasharray="3 3"
                opacity="0.8"
              />
              {/* Highlight point on historical line */}
              {hoveredPoint.isHistory && (
                <circle
                  cx={getX(hoverIndex)}
                  cy={getY(axisConfig.getVal(hoveredPoint))}
                  r="5"
                  fill="#94a3b8"
                  stroke="#0f172a"
                  strokeWidth="2"
                />
              )}
              {/* Highlight point on forecast line */}
              {!hoveredPoint.isHistory && (
                <circle
                  cx={getX(hoverIndex)}
                  cy={getY(axisConfig.getPred(hoveredPoint) ?? axisConfig.getVal(hoveredPoint))}
                  r="5"
                  fill={axisConfig.color}
                  stroke="#0f172a"
                  strokeWidth="2"
                />
              )}

            </g>
          )}

          {/* Time axis labels */}
          <g>
            <text
              x={50}
              y={310}
              fill="#64748b"
              fontSize="10"
              fontFamily="monospace"
            >
              {activePoints[0]?.time.split(' ')[0]} 00:00
            </text>
            {nowX !== null && nowX > 50 && nowX < 950 && (
              <text
                x={nowX}
                y={310}
                fill="#22d3ee"
                fontSize="10"
                fontWeight="600"
                fontFamily="monospace"
                textAnchor="middle"
              >
                Day 7 End
              </text>
            )}
            <text
              x={950}
              y={310}
              fill="#64748b"
              fontSize="10"
              fontFamily="monospace"
              textAnchor="end"
            >
              {activePoints[activePoints.length - 1]?.time.split(' ')[0]} 23:45 (Day 8 End)
            </text>
          </g>
        </svg>

        {/* Dynamic Hover Tooltip HUD */}
        {hoveredPoint && hoverIndex !== null && (
          <div
            className="absolute z-20 bg-slate-950/95 border border-slate-700 rounded-lg p-3 shadow-2xl text-xs backdrop-blur-md pointer-events-none transition-all duration-75"
            style={{
              left: Math.min(
                Math.max(10, (getX(hoverIndex) / 1000) * 100 - 10),
                70
              ) + '%',
              top: '15px'
            }}
          >
            <div className="flex items-center justify-between gap-3 border-b border-slate-700 pb-1.5 mb-1.5">
              <span className="font-mono text-cyan-300 font-semibold">{hoveredPoint.time}</span>
              <span
                className={`px-1.5 py-0.5 rounded text-[10px] font-bold uppercase ${
                  hoveredPoint.isHistory
                    ? 'bg-slate-800 text-slate-300'
                    : 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/40'
                }`}
              >
                {hoveredPoint.isHistory ? 'Historical' : `Day 8 Forecast (${selectedModel.toUpperCase()})`}
              </span>
            </div>

            <div className="space-y-1 font-mono">
              {hoveredPoint.isHistory ? (
                <div className="flex justify-between gap-4">
                  <span className="text-slate-400">Observed Error:</span>
                  <span className="text-white font-bold">
                    {axisConfig.getVal(hoveredPoint).toFixed(4)} m
                  </span>
                </div>
              ) : (
                <>
                  <div className="flex justify-between gap-4">
                    <span className="text-cyan-400 font-medium">Model Forecast (ŷ):</span>
                    <span className="text-cyan-300 font-bold">
                      {(axisConfig.getPred(hoveredPoint) ?? 0).toFixed(4)} m
                    </span>
                  </div>
                  {axisConfig.getLower(hoveredPoint) !== undefined && (
                    <div className="flex justify-between gap-4 text-[11px] text-slate-400">
                      <span>95% Prediction Band:</span>
                      <span className="text-slate-300">
                        [{axisConfig.getLower(hoveredPoint)?.toFixed(3)}, {axisConfig.getUpper(hoveredPoint)?.toFixed(3)}] m
                      </span>
                    </div>
                  )}

                </>
              )}
            </div>
          </div>
        )}

        {/* Legend */}
        <div className="flex flex-wrap items-center justify-between gap-4 mt-4 pt-3 border-t border-slate-700/80 text-xs">
          <div className="flex flex-wrap items-center gap-5">
            <div className="flex items-center gap-2">
              <span className="w-4 h-1 bg-slate-400 rounded"></span>
              <span className="text-slate-300 font-medium">Historical Error (Days 1–7)</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="w-4 h-1 bg-cyan-400 rounded"></span>
              <span className="text-cyan-300 font-medium">AI Forecast (Day 8: {selectedModel.toUpperCase()})</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="w-3.5 h-3.5 bg-cyan-500/20 border border-cyan-500/40 rounded-sm"></span>
              <span className="text-slate-400">95% Prediction Interval (data-driven)</span>
            </div>
          </div>

          <div className="flex items-center gap-3 text-slate-400 font-mono text-[11px]">
            <span className="flex items-center gap-1 text-emerald-400">
              <CheckCircle2 className="w-3.5 h-3.5" />
              Day 8 RMSE: {forecastResult.metrics.clockRMSE.toFixed(4)} m
            </span>
            <span>|</span>
            <span className="text-slate-300">
              MAE: {forecastResult.metrics.clockMAE.toFixed(4)} m
            </span>
          </div>
        </div>
      </div>
    </div>
  );
};